#!/bin/bash
read x 

x=1
sum=0

while [ $x -le $y ]
do
  read num               #get number
  sum=$((sum + num))     #sum+=num
  i=$((i + 1))
done

$avg = $( echo "$sum / $x" | bc -l )
printf "%0.2f" $avg
